<?php

namespace App\Filament\Resources\VentureSectionConfigResource\Pages;

use App\Filament\Resources\VentureSectionConfigResource;
use App\Models\VentureSectionConfig;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use Filament\Tables;
use Filament\Tables\Table;
use Filament\Notifications\Notification;

class ListVentureSectionConfigs extends ListRecords
{
    protected static string $resource = VentureSectionConfigResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make(),
            Actions\Action::make('seedDefaults')
                ->label('Seed Defaults')
                ->color('warning')
                ->icon('heroicon-o-arrow-down-tray')
                ->action(fn () => $this->seedDefaultConfigs()),
        ];
    }

    public function table(Table $table): Table
    {
        return $table
            ->query(VentureSectionConfig::query()->orderBy('tab_slug')->orderBy('sort_order'))
            ->columns(VentureSectionConfig::columns())
            ->filters([
                Tables\Filters\SelectFilter::make('tab_slug')
                    ->options([
                        'dashboard' => 'Dashboard',
                        'strategic_frameworks' => 'Strategic Frameworks',
                        'market_analysis' => 'Market Analysis',
                        'financial_projections' => 'Financial Projections',
                        'mvp_roadmap' => 'MVP Roadmap',
                        'risk_assessment' => 'Risk Assessment',
                        'go_to_market' => 'Go to Market',
                        'competitive_analysis' => 'Competitive Analysis',
                    ]),
                Tables\Filters\TernaryFilter::make('is_visible'),
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Tables\Actions\DeleteAction::make(),
            ])
            ->groupedBulkActions([
                Tables\Actions\DeleteBulkAction::make(),
            ])
            ->groups([
                Tables\Grouping\Group::make('tab_slug')
                    ->collapsible(),
            ]);
    }

    protected function seedDefaultConfigs(): void
    {
        $defaults = [
            // Tab 1 - Market Analysis (1-8 sections)
            [
                'tab_slug' => 'tab_1',
                'section_slug' => 'market_overview',
                'label_en' => 'Market Overview',
                'label_ar' => 'نظرة عامة على السوق',
                'component_type' => 'textarea',
                'icon' => 'chart-bar',
                'color' => 'blue',
                'sort_order' => 1,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_1',
                'section_slug' => 'target_audience',
                'label_en' => 'Target Audience',
                'label_ar' => 'الجمهور المستهدف',
                'component_type' => 'textarea',
                'icon' => 'users',
                'color' => 'green',
                'sort_order' => 2,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_1',
                'section_slug' => 'market_size',
                'label_en' => 'Market Size & Potential',
                'label_ar' => 'حجم السوق والإمكانات',
                'component_type' => 'textarea',
                'icon' => 'chart-pie',
                'color' => 'purple',
                'sort_order' => 3,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_1',
                'section_slug' => 'competitor_analysis',
                'label_en' => 'Competitor Analysis',
                'label_ar' => 'تحليل المنافسين',
                'component_type' => 'textarea',
                'icon' => 'flag',
                'color' => 'red',
                'sort_order' => 4,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_1',
                'section_slug' => 'market_trends',
                'label_en' => 'Market Trends',
                'label_ar' => 'اتجاهات السوق',
                'component_type' => 'textarea',
                'icon' => 'trending-up',
                'color' => 'amber',
                'sort_order' => 5,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_1',
                'section_slug' => 'market_entry',
                'label_en' => 'Market Entry Strategy',
                'label_ar' => 'استراتيجية الدخول إلى السوق',
                'component_type' => 'textarea',
                'icon' => 'arrow-right',
                'color' => 'cyan',
                'sort_order' => 6,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_1',
                'section_slug' => 'regulatory_environment',
                'label_en' => 'Regulatory Environment',
                'label_ar' => 'البيئة التنظيمية',
                'component_type' => 'textarea',
                'icon' => 'document-check',
                'color' => 'slate',
                'sort_order' => 7,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_1',
                'section_slug' => 'market_gaps',
                'label_en' => 'Market Gaps & Opportunities',
                'label_ar' => 'الفجوات والفرص في السوق',
                'component_type' => 'textarea',
                'icon' => 'light-bulb',
                'color' => 'yellow',
                'sort_order' => 8,
                'is_visible' => true,
            ],

            // Tab 2 - Product Strategy (9-16 sections)
            [
                'tab_slug' => 'tab_2',
                'section_slug' => 'product_description',
                'label_en' => 'Product Description',
                'label_ar' => 'وصف المنتج',
                'component_type' => 'textarea',
                'icon' => 'cube',
                'color' => 'blue',
                'sort_order' => 1,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_2',
                'section_slug' => 'product_features',
                'label_en' => 'Key Features & Benefits',
                'label_ar' => 'الميزات والفوائد الرئيسية',
                'component_type' => 'textarea',
                'icon' => 'sparkles',
                'color' => 'indigo',
                'sort_order' => 2,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_2',
                'section_slug' => 'product_differentiation',
                'label_en' => 'Differentiation Strategy',
                'label_ar' => 'استراتيجية التمييز',
                'component_type' => 'textarea',
                'icon' => 'star',
                'color' => 'amber',
                'sort_order' => 3,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_2',
                'section_slug' => 'product_roadmap',
                'label_en' => 'Product Roadmap',
                'label_ar' => 'خريطة الطريق',
                'component_type' => 'textarea',
                'icon' => 'map',
                'color' => 'green',
                'sort_order' => 4,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_2',
                'section_slug' => 'pricing_strategy',
                'label_en' => 'Pricing Strategy',
                'label_ar' => 'استراتيجية التسعير',
                'component_type' => 'textarea',
                'icon' => 'banknote',
                'color' => 'green',
                'sort_order' => 5,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_2',
                'section_slug' => 'product_development',
                'label_en' => 'Product Development Plan',
                'label_ar' => 'خطة تطوير المنتج',
                'component_type' => 'textarea',
                'icon' => 'wrench-screwdriver',
                'color' => 'orange',
                'sort_order' => 6,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_2',
                'section_slug' => 'quality_assurance',
                'label_en' => 'Quality Assurance',
                'label_ar' => 'ضمان الجودة',
                'component_type' => 'textarea',
                'icon' => 'check-badge',
                'color' => 'cyan',
                'sort_order' => 7,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_2',
                'section_slug' => 'intellectual_property',
                'label_en' => 'Intellectual Property',
                'label_ar' => 'الملكية الفكرية',
                'component_type' => 'textarea',
                'icon' => 'lock-closed',
                'color' => 'purple',
                'sort_order' => 8,
                'is_visible' => true,
            ],

            // Tab 3 - Financial Model (17-24 sections)
            [
                'tab_slug' => 'tab_3',
                'section_slug' => 'revenue_model',
                'label_en' => 'Revenue Model',
                'label_ar' => 'نموذج الإيرادات',
                'component_type' => 'textarea',
                'icon' => 'currency-dollar',
                'color' => 'green',
                'sort_order' => 1,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_3',
                'section_slug' => 'cost_structure',
                'label_en' => 'Cost Structure',
                'label_ar' => 'هيكل التكاليف',
                'component_type' => 'textarea',
                'icon' => 'calculator',
                'color' => 'red',
                'sort_order' => 2,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_3',
                'section_slug' => 'financial_projections',
                'label_en' => 'Financial Projections',
                'label_ar' => 'التوقعات المالية',
                'component_type' => 'textarea',
                'icon' => 'chart-line',
                'color' => 'blue',
                'sort_order' => 3,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_3',
                'section_slug' => 'break_even_analysis',
                'label_en' => 'Break-Even Analysis',
                'label_ar' => 'تحليل نقطة التعادل',
                'component_type' => 'textarea',
                'icon' => 'chart-bar',
                'color' => 'orange',
                'sort_order' => 4,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_3',
                'section_slug' => 'funding_requirements',
                'label_en' => 'Funding Requirements',
                'label_ar' => 'متطلبات التمويل',
                'component_type' => 'textarea',
                'icon' => 'banknote',
                'color' => 'amber',
                'sort_order' => 5,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_3',
                'section_slug' => 'use_of_funds',
                'label_en' => 'Use of Funds',
                'label_ar' => 'استخدام التمويل',
                'component_type' => 'textarea',
                'icon' => 'arrow-trending-up',
                'color' => 'cyan',
                'sort_order' => 6,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_3',
                'section_slug' => 'unit_economics',
                'label_en' => 'Unit Economics',
                'label_ar' => 'الاقتصاد على مستوى الوحدة',
                'component_type' => 'textarea',
                'icon' => 'square-3-stack-3d',
                'color' => 'indigo',
                'sort_order' => 7,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_3',
                'section_slug' => 'cash_flow_analysis',
                'label_en' => 'Cash Flow Analysis',
                'label_ar' => 'تحليل التدفقات النقدية',
                'component_type' => 'textarea',
                'icon' => 'chart-pie',
                'color' => 'purple',
                'sort_order' => 8,
                'is_visible' => true,
            ],

            // Tab 4 - Operations (25-32 sections)
            [
                'tab_slug' => 'tab_4',
                'section_slug' => 'operations_overview',
                'label_en' => 'Operations Overview',
                'label_ar' => 'نظرة عامة على العمليات',
                'component_type' => 'textarea',
                'icon' => 'cog-6-tooth',
                'color' => 'blue',
                'sort_order' => 1,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_4',
                'section_slug' => 'supply_chain',
                'label_en' => 'Supply Chain',
                'label_ar' => 'سلسلة التوريد',
                'component_type' => 'textarea',
                'icon' => 'truck',
                'color' => 'orange',
                'sort_order' => 2,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_4',
                'section_slug' => 'production_process',
                'label_en' => 'Production Process',
                'label_ar' => 'عملية الإنتاج',
                'component_type' => 'textarea',
                'icon' => 'wrench-screwdriver',
                'color' => 'amber',
                'sort_order' => 3,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_4',
                'section_slug' => 'facilities_equipment',
                'label_en' => 'Facilities & Equipment',
                'label_ar' => 'المرافق والمعدات',
                'component_type' => 'textarea',
                'icon' => 'building-office',
                'color' => 'slate',
                'sort_order' => 4,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_4',
                'section_slug' => 'quality_control',
                'label_en' => 'Quality Control',
                'label_ar' => 'مراقبة الجودة',
                'component_type' => 'textarea',
                'icon' => 'check-circle',
                'color' => 'green',
                'sort_order' => 5,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_4',
                'section_slug' => 'customer_support',
                'label_en' => 'Customer Support',
                'label_ar' => 'دعم العملاء',
                'component_type' => 'textarea',
                'icon' => 'users',
                'color' => 'cyan',
                'sort_order' => 6,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_4',
                'section_slug' => 'technology_infrastructure',
                'label_en' => 'Technology Infrastructure',
                'label_ar' => 'البنية التحتية التكنولوجية',
                'component_type' => 'textarea',
                'icon' => 'server',
                'color' => 'indigo',
                'sort_order' => 7,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_4',
                'section_slug' => 'partnerships_vendors',
                'label_en' => 'Partnerships & Vendors',
                'label_ar' => 'الشراكات والموردون',
                'component_type' => 'textarea',
                'icon' => 'handshake',
                'color' => 'purple',
                'sort_order' => 8,
                'is_visible' => true,
            ],

            // Tab 5 - Team (33-40 sections)
            [
                'tab_slug' => 'tab_5',
                'section_slug' => 'team_composition',
                'label_en' => 'Team Composition',
                'label_ar' => 'تكوين الفريق',
                'component_type' => 'textarea',
                'icon' => 'users-plus',
                'color' => 'blue',
                'sort_order' => 1,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_5',
                'section_slug' => 'leadership_team',
                'label_en' => 'Leadership Team',
                'label_ar' => 'فريق القيادة',
                'component_type' => 'textarea',
                'icon' => 'shield-check',
                'color' => 'amber',
                'sort_order' => 2,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_5',
                'section_slug' => 'key_competencies',
                'label_en' => 'Key Competencies',
                'label_ar' => 'الكفاءات الرئيسية',
                'component_type' => 'textarea',
                'icon' => 'academic-cap',
                'color' => 'green',
                'sort_order' => 3,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_5',
                'section_slug' => 'organizational_structure',
                'label_en' => 'Organizational Structure',
                'label_ar' => 'الهيكل التنظيمي',
                'component_type' => 'textarea',
                'icon' => 'square-3-stack-3d',
                'color' => 'orange',
                'sort_order' => 4,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_5',
                'section_slug' => 'hiring_plan',
                'label_en' => 'Hiring Plan',
                'label_ar' => 'خطة التوظيف',
                'component_type' => 'textarea',
                'icon' => 'briefcase',
                'color' => 'cyan',
                'sort_order' => 5,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_5',
                'section_slug' => 'compensation_culture',
                'label_en' => 'Compensation & Culture',
                'label_ar' => 'التعويض والثقافة',
                'component_type' => 'textarea',
                'icon' => 'heart',
                'color' => 'red',
                'sort_order' => 6,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_5',
                'section_slug' => 'advisory_board',
                'label_en' => 'Advisory Board',
                'label_ar' => 'مجلس الاستشارة',
                'component_type' => 'textarea',
                'icon' => 'users-group',
                'color' => 'purple',
                'sort_order' => 7,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_5',
                'section_slug' => 'succession_planning',
                'label_en' => 'Succession Planning',
                'label_ar' => 'التخطيط للخلافة',
                'component_type' => 'textarea',
                'icon' => 'arrow-trending-up',
                'color' => 'indigo',
                'sort_order' => 8,
                'is_visible' => true,
            ],

            // Tab 6 - Risk Assessment (41-48 sections)
            [
                'tab_slug' => 'tab_6',
                'section_slug' => 'risk_identification',
                'label_en' => 'Risk Identification',
                'label_ar' => 'تحديد المخاطر',
                'component_type' => 'textarea',
                'icon' => 'exclamation-triangle',
                'color' => 'red',
                'sort_order' => 1,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_6',
                'section_slug' => 'market_risks',
                'label_en' => 'Market Risks',
                'label_ar' => 'مخاطر السوق',
                'component_type' => 'textarea',
                'icon' => 'chart-bar',
                'color' => 'orange',
                'sort_order' => 2,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_6',
                'section_slug' => 'operational_risks',
                'label_en' => 'Operational Risks',
                'label_ar' => 'المخاطر التشغيلية',
                'component_type' => 'textarea',
                'icon' => 'wrench-screwdriver',
                'color' => 'amber',
                'sort_order' => 3,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_6',
                'section_slug' => 'financial_risks',
                'label_en' => 'Financial Risks',
                'label_ar' => 'المخاطر المالية',
                'component_type' => 'textarea',
                'icon' => 'banknote',
                'color' => 'red',
                'sort_order' => 4,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_6',
                'section_slug' => 'technological_risks',
                'label_en' => 'Technological Risks',
                'label_ar' => 'المخاطر التكنولوجية',
                'component_type' => 'textarea',
                'icon' => 'server',
                'color' => 'purple',
                'sort_order' => 5,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_6',
                'section_slug' => 'mitigation_strategies',
                'label_en' => 'Mitigation Strategies',
                'label_ar' => 'استراتيجيات التخفيف',
                'component_type' => 'textarea',
                'icon' => 'shield-check',
                'color' => 'green',
                'sort_order' => 6,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_6',
                'section_slug' => 'contingency_planning',
                'label_en' => 'Contingency Planning',
                'label_ar' => 'التخطيط للطوارئ',
                'component_type' => 'textarea',
                'icon' => 'arrow-path',
                'color' => 'blue',
                'sort_order' => 7,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_6',
                'section_slug' => 'insurance_coverage',
                'label_en' => 'Insurance Coverage',
                'label_ar' => 'تغطية التأمين',
                'component_type' => 'textarea',
                'icon' => 'document-check',
                'color' => 'slate',
                'sort_order' => 8,
                'is_visible' => true,
            ],

            // Tab 7 - Growth Strategy (49-56 sections)
            [
                'tab_slug' => 'tab_7',
                'section_slug' => 'growth_vision',
                'label_en' => 'Growth Vision',
                'label_ar' => 'رؤية النمو',
                'component_type' => 'textarea',
                'icon' => 'star',
                'color' => 'amber',
                'sort_order' => 1,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_7',
                'section_slug' => 'market_expansion',
                'label_en' => 'Market Expansion Strategy',
                'label_ar' => 'استراتيجية توسع السوق',
                'component_type' => 'textarea',
                'icon' => 'arrow-trending-up',
                'color' => 'green',
                'sort_order' => 2,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_7',
                'section_slug' => 'product_expansion',
                'label_en' => 'Product Line Expansion',
                'label_ar' => 'توسع خط المنتجات',
                'component_type' => 'textarea',
                'icon' => 'cube',
                'color' => 'blue',
                'sort_order' => 3,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_7',
                'section_slug' => 'strategic_partnerships',
                'label_en' => 'Strategic Partnerships',
                'label_ar' => 'الشراكات الاستراتيجية',
                'component_type' => 'textarea',
                'icon' => 'handshake',
                'color' => 'purple',
                'sort_order' => 4,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_7',
                'section_slug' => 'acquisition_strategy',
                'label_en' => 'Acquisition Strategy',
                'label_ar' => 'استراتيجية الاستحواذ',
                'component_type' => 'textarea',
                'icon' => 'chart-bar',
                'color' => 'orange',
                'sort_order' => 5,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_7',
                'section_slug' => 'international_expansion',
                'label_en' => 'International Expansion',
                'label_ar' => 'التوسع الدولي',
                'component_type' => 'textarea',
                'icon' => 'globe-alt',
                'color' => 'cyan',
                'sort_order' => 6,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_7',
                'section_slug' => 'technology_roadmap',
                'label_en' => 'Technology Roadmap',
                'label_ar' => 'خريطة طريق التكنولوجيا',
                'component_type' => 'textarea',
                'icon' => 'code-bracket',
                'color' => 'indigo',
                'sort_order' => 7,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_7',
                'section_slug' => 'sustainability_vision',
                'label_en' => 'Sustainability Vision',
                'label_ar' => 'رؤية الاستدامة',
                'component_type' => 'textarea',
                'icon' => 'leaf',
                'color' => 'green',
                'sort_order' => 8,
                'is_visible' => true,
            ],

            // Tab 8 - Implementation (57-64 sections) - Note: Will be limited to 51 total, so only 7 more
            [
                'tab_slug' => 'tab_8',
                'section_slug' => 'implementation_timeline',
                'label_en' => 'Implementation Timeline',
                'label_ar' => 'جدول التنفيذ',
                'component_type' => 'textarea',
                'icon' => 'calendar',
                'color' => 'blue',
                'sort_order' => 1,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_8',
                'section_slug' => 'milestones',
                'label_en' => 'Key Milestones',
                'label_ar' => 'الإنجازات الرئيسية',
                'component_type' => 'textarea',
                'icon' => 'flag',
                'color' => 'green',
                'sort_order' => 2,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_8',
                'section_slug' => 'success_metrics',
                'label_en' => 'Success Metrics',
                'label_ar' => 'مقاييس النجاح',
                'component_type' => 'textarea',
                'icon' => 'chart-bar',
                'color' => 'orange',
                'sort_order' => 3,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_8',
                'section_slug' => 'kpis',
                'label_en' => 'Key Performance Indicators',
                'label_ar' => 'مؤشرات الأداء الرئيسية',
                'component_type' => 'textarea',
                'icon' => 'chart-pie',
                'color' => 'amber',
                'sort_order' => 4,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_8',
                'section_slug' => 'monitoring_evaluation',
                'label_en' => 'Monitoring & Evaluation',
                'label_ar' => 'المراقبة والتقييم',
                'component_type' => 'textarea',
                'icon' => 'eye',
                'color' => 'purple',
                'sort_order' => 5,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_8',
                'section_slug' => 'resource_allocation',
                'label_en' => 'Resource Allocation',
                'label_ar' => 'تخصيص الموارد',
                'component_type' => 'textarea',
                'icon' => 'square-3-stack-3d',
                'color' => 'cyan',
                'sort_order' => 6,
                'is_visible' => true,
            ],
            [
                'tab_slug' => 'tab_8',
                'section_slug' => 'exit_strategy',
                'label_en' => 'Exit Strategy',
                'label_ar' => 'استراتيجية الخروج',
                'component_type' => 'textarea',
                'icon' => 'arrow-right-on-rectangle',
                'color' => 'red',
                'sort_order' => 7,
                'is_visible' => true,
            ],
        ];

        // Check if configs already exist
        $existingCount = VentureSectionConfig::count();

        if ($existingCount === 0) {
            VentureSectionConfig::insert($defaults);
            Notification::make()
                ->title('Success')
                ->body('Successfully seeded ' . count($defaults) . ' default section configurations.')
                ->success()
                ->send();
        } else {
            Notification::make()
                ->title('Already Exists')
                ->body('Section configurations already exist. Skipping seed operation.')
                ->warning()
                ->send();
        }
    }
}
