<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\NafathNationalityCode;

class NafathNationalityCodeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $nafathCodes = [
            // Gulf Countries (101-113)
            ['code' => '101', 'name_en' => 'United Arab Emirates', 'name_ar' => 'الامارات العربية'],
            ['code' => '102', 'name_en' => 'Jordan', 'name_ar' => 'الاردن'],
            ['code' => '103', 'name_en' => 'Bahrain', 'name_ar' => 'البحرين'],
            ['code' => '104', 'name_en' => 'Syria', 'name_ar' => 'سوريا'],
            ['code' => '105', 'name_en' => 'Iraq', 'name_ar' => 'العراق'],
            ['code' => '106', 'name_en' => 'Oman', 'name_ar' => 'عمان'],
            ['code' => '107', 'name_en' => 'Palestine', 'name_ar' => 'فلسطين'],
            ['code' => '108', 'name_en' => 'Qatar', 'name_ar' => 'قطر'],
            ['code' => '109', 'name_en' => 'Kuwait', 'name_ar' => 'الكويت'],
            ['code' => '110', 'name_en' => 'Lebanon', 'name_ar' => 'لبنان'],
            ['code' => '111', 'name_en' => 'Yemen', 'name_ar' => 'اليمن'],
            ['code' => '113', 'name_en' => 'Saudi Arabia', 'name_ar' => 'العربية السعودية'],

            // North Africa (201-209)
            ['code' => '201', 'name_en' => 'Tunisia', 'name_ar' => 'تونس'],
            ['code' => '202', 'name_en' => 'Algeria', 'name_ar' => 'الجزائر'],
            ['code' => '203', 'name_en' => 'Djibouti', 'name_ar' => 'جيبوتى'],
            ['code' => '204', 'name_en' => 'Sudan', 'name_ar' => 'السودان'],
            ['code' => '205', 'name_en' => 'Somalia', 'name_ar' => 'الصومال'],
            ['code' => '206', 'name_en' => 'Libya', 'name_ar' => 'ليبيا'],
            ['code' => '207', 'name_en' => 'Egypt', 'name_ar' => 'مصر'],
            ['code' => '208', 'name_en' => 'Morocco', 'name_ar' => 'المغرب'],
            ['code' => '209', 'name_en' => 'Mauritania', 'name_ar' => 'موريتانيا'],

            // Asia (301-340)
            ['code' => '301', 'name_en' => 'Afghanistan', 'name_ar' => 'افغانستان'],
            ['code' => '302', 'name_en' => 'Indonesia', 'name_ar' => 'اندونيسيا'],
            ['code' => '303', 'name_en' => 'Iran', 'name_ar' => 'ايران'],
            ['code' => '304', 'name_en' => 'Pakistan', 'name_ar' => 'باكستان'],
            ['code' => '305', 'name_en' => 'Bangladesh', 'name_ar' => 'بنجلاديش'],
            ['code' => '306', 'name_en' => 'Brunei', 'name_ar' => 'بروني'],
            ['code' => '307', 'name_en' => 'Myanmar', 'name_ar' => 'جمهورية ميانمار'],
            ['code' => '308', 'name_en' => 'Thailand', 'name_ar' => 'تايلند'],
            ['code' => '309', 'name_en' => 'Turkey', 'name_ar' => 'تركيا'],
            ['code' => '310', 'name_en' => 'Maldives', 'name_ar' => 'جزر مالديف'],
            ['code' => '311', 'name_en' => 'Russia', 'name_ar' => 'روسيا الاتحادية'],
            ['code' => '312', 'name_en' => 'Singapore', 'name_ar' => 'سنغافورة'],
            ['code' => '313', 'name_en' => 'Sri Lanka', 'name_ar' => 'سري لنكا'],
            ['code' => '315', 'name_en' => 'Philippines', 'name_ar' => 'الفلبين'],
            ['code' => '316', 'name_en' => 'Vietnam', 'name_ar' => 'فيتنام'],
            ['code' => '317', 'name_en' => 'Cambodia', 'name_ar' => 'كمبوديا'],
            ['code' => '318', 'name_en' => 'South Korea', 'name_ar' => 'كوريا الجنوبية'],
            ['code' => '319', 'name_en' => 'Malaysia', 'name_ar' => 'ماليزيا'],
            ['code' => '320', 'name_en' => 'Nepal', 'name_ar' => 'نيبال'],
            ['code' => '321', 'name_en' => 'India', 'name_ar' => 'الهند'],
            ['code' => '322', 'name_en' => 'Hong Kong', 'name_ar' => 'هونج كونج'],
            ['code' => '323', 'name_en' => 'Japan', 'name_ar' => 'اليابان'],
            ['code' => '324', 'name_en' => 'Bhutan', 'name_ar' => 'بهوتان'],
            ['code' => '325', 'name_en' => 'China', 'name_ar' => 'الصين الشعبية'],
            ['code' => '326', 'name_en' => 'Cyprus', 'name_ar' => 'قبرص'],
            ['code' => '328', 'name_en' => 'North Korea', 'name_ar' => 'كوريا الشمالية'],
            ['code' => '329', 'name_en' => 'Laos', 'name_ar' => 'لاوس'],
            ['code' => '330', 'name_en' => 'Mongolia', 'name_ar' => 'منغوليا'],
            ['code' => '331', 'name_en' => 'Macao', 'name_ar' => 'ماكاو'],
            ['code' => '332', 'name_en' => 'Turkistan', 'name_ar' => 'تركستان'],
            ['code' => '335', 'name_en' => 'Tribes Emigrated', 'name_ar' => 'القبائل النازحة'],
            ['code' => '336', 'name_en' => 'Kazakhstan', 'name_ar' => 'كازاخستان'],
            ['code' => '337', 'name_en' => 'Uzbekistan', 'name_ar' => 'ازبكستان'],
            ['code' => '338', 'name_en' => 'Turkmenistan', 'name_ar' => 'تركمانستان'],
            ['code' => '339', 'name_en' => 'Tajikistan', 'name_ar' => 'طاجكستان'],
            ['code' => '340', 'name_en' => 'Kyrgyzstan', 'name_ar' => 'قرغيزستان'],
            ['code' => '343', 'name_en' => 'Azerbaijan', 'name_ar' => 'اذربيجان'],
            ['code' => '344', 'name_en' => 'Chechnya', 'name_ar' => 'الشاشان'],
            ['code' => '345', 'name_en' => 'Dagestan', 'name_ar' => 'داغستان'],
            ['code' => '346', 'name_en' => 'Anquosh', 'name_ar' => 'انقوش'],
            ['code' => '347', 'name_en' => 'Tatarstan', 'name_ar' => 'تتارستان'],
            ['code' => '349', 'name_en' => 'East Timor', 'name_ar' => 'تيمور الشرقية'],

            // Africa (401-454)
            ['code' => '401', 'name_en' => 'Ethiopia', 'name_ar' => 'اثيوبيا'],
            ['code' => '402', 'name_en' => 'Uganda', 'name_ar' => 'اوغندة'],
            ['code' => '403', 'name_en' => 'Botswana', 'name_ar' => 'بوتسوانا'],
            ['code' => '404', 'name_en' => 'Burundi', 'name_ar' => 'بورندي'],
            ['code' => '405', 'name_en' => 'Chad', 'name_ar' => 'تشاد'],
            ['code' => '406', 'name_en' => 'Tanzania', 'name_ar' => 'تنزانيا'],
            ['code' => '407', 'name_en' => 'Togo', 'name_ar' => 'توجو'],
            ['code' => '408', 'name_en' => 'Gabon', 'name_ar' => 'جابون'],
            ['code' => '409', 'name_en' => 'Gambia', 'name_ar' => 'غامبيا'],
            ['code' => '410', 'name_en' => 'Comoros', 'name_ar' => 'جزر القمر'],
            ['code' => '411', 'name_en' => 'South Africa', 'name_ar' => 'جنوب افريقيا'],
            ['code' => '412', 'name_en' => 'Namibia', 'name_ar' => 'ناميبيا'],
            ['code' => '413', 'name_en' => 'Benin', 'name_ar' => 'بنين'],
            ['code' => '414', 'name_en' => 'Rwanda', 'name_ar' => 'رواندا'],
            ['code' => '415', 'name_en' => 'Zimbabwe', 'name_ar' => 'زمبابوي'],
            ['code' => '416', 'name_en' => 'Zaire', 'name_ar' => 'زائير'],
            ['code' => '417', 'name_en' => 'Zambia', 'name_ar' => 'زامبيا'],
            ['code' => '418', 'name_en' => 'Ivory Coast', 'name_ar' => 'ساحل العاج'],
            ['code' => '419', 'name_en' => 'Senegal', 'name_ar' => 'السنغال'],
            ['code' => '420', 'name_en' => 'Sierra Leone', 'name_ar' => 'سيراليون'],
            ['code' => '421', 'name_en' => 'Ghana', 'name_ar' => 'غانا'],
            ['code' => '422', 'name_en' => 'Guinea', 'name_ar' => 'غينيا'],
            ['code' => '423', 'name_en' => 'Guinea Bissau', 'name_ar' => 'غينيابيساو'],
            ['code' => '424', 'name_en' => 'Burkina Faso', 'name_ar' => 'بوركينافاسو'],
            ['code' => '425', 'name_en' => 'Cameroon', 'name_ar' => 'الكاميرون'],
            ['code' => '426', 'name_en' => 'Congo', 'name_ar' => 'الكونغو'],
            ['code' => '427', 'name_en' => 'Kenya', 'name_ar' => 'كينيا'],
            ['code' => '428', 'name_en' => 'Lesotho', 'name_ar' => 'ليسوتو'],
            ['code' => '429', 'name_en' => 'Liberia', 'name_ar' => 'ليبيريا'],
            ['code' => '430', 'name_en' => 'Mali', 'name_ar' => 'مالي'],
            ['code' => '432', 'name_en' => 'Malawi', 'name_ar' => 'ملاوي'],
            ['code' => '433', 'name_en' => 'Mauritius', 'name_ar' => 'موريشيوس'],
            ['code' => '434', 'name_en' => 'Mozambique', 'name_ar' => 'موزمبيق'],
            ['code' => '435', 'name_en' => 'Nigeria', 'name_ar' => 'نيجيريا'],
            ['code' => '436', 'name_en' => 'Niger', 'name_ar' => 'النيجر'],
            ['code' => '437', 'name_en' => 'Central Africa', 'name_ar' => 'افريقيا الوسطى'],
            ['code' => '438', 'name_en' => 'Angola', 'name_ar' => 'انجولا'],
            ['code' => '439', 'name_en' => 'Cape Verde', 'name_ar' => 'الراس الاخضر'],
            ['code' => '440', 'name_en' => 'Equatorial Guinea', 'name_ar' => 'غينيا الاستوائية'],
            ['code' => '441', 'name_en' => 'Madagascar', 'name_ar' => 'ملاجاسي'],
            ['code' => '442', 'name_en' => 'São Tomé and Príncipe', 'name_ar' => 'ساوتومي/برنسبى'],
            ['code' => '443', 'name_en' => 'Seychelles', 'name_ar' => 'جزر سيشل'],
            ['code' => '444', 'name_en' => 'Swaziland', 'name_ar' => 'سوزيلاند'],
            ['code' => '449', 'name_en' => 'Eritrea', 'name_ar' => 'ارتيريا'],
            ['code' => '453', 'name_en' => 'South Sudan', 'name_ar' => 'جمهورية جنوب السودان'],
            ['code' => '454', 'name_en' => 'Cape Verde', 'name_ar' => 'كاب فيرد'],

            // Europe (501-555)
            ['code' => '501', 'name_en' => 'Spain', 'name_ar' => 'اسبانيا'],
            ['code' => '502', 'name_en' => 'Albania', 'name_ar' => 'البانيا'],
            ['code' => '503', 'name_en' => 'Germany', 'name_ar' => 'المانيا'],
            ['code' => '504', 'name_en' => 'Ireland', 'name_ar' => 'ايرلندا'],
            ['code' => '505', 'name_en' => 'Italy', 'name_ar' => 'ايطاليا'],
            ['code' => '506', 'name_en' => 'United Kingdom', 'name_ar' => 'المملكة المتحدة'],
            ['code' => '507', 'name_en' => 'Portugal', 'name_ar' => 'البرتغال'],
            ['code' => '508', 'name_en' => 'Bulgaria', 'name_ar' => 'بلغاريا'],
            ['code' => '509', 'name_en' => 'Belgium', 'name_ar' => 'بلجيكا'],
            ['code' => '510', 'name_en' => 'Poland', 'name_ar' => 'بولندا'],
            ['code' => '512', 'name_en' => 'Denmark', 'name_ar' => 'الدانمارك'],
            ['code' => '513', 'name_en' => 'Romania', 'name_ar' => 'رومانيا'],
            ['code' => '514', 'name_en' => 'Sweden', 'name_ar' => 'السويد'],
            ['code' => '515', 'name_en' => 'Switzerland', 'name_ar' => 'سويسرا'],
            ['code' => '516', 'name_en' => 'France', 'name_ar' => 'فرنسا'],
            ['code' => '517', 'name_en' => 'Finland', 'name_ar' => 'فنلندا'],
            ['code' => '518', 'name_en' => 'Serbia', 'name_ar' => 'صربيا'],
            ['code' => '519', 'name_en' => 'Netherlands', 'name_ar' => 'هولندا'],
            ['code' => '521', 'name_en' => 'Greece', 'name_ar' => 'اليونان'],
            ['code' => '522', 'name_en' => 'Andorra', 'name_ar' => 'اندورا'],
            ['code' => '523', 'name_en' => 'Austria', 'name_ar' => 'النمسا'],
            ['code' => '524', 'name_en' => 'Montenegro', 'name_ar' => 'الجبل الأسود'],
            ['code' => '525', 'name_en' => 'Hungary', 'name_ar' => 'هنغاريا'],
            ['code' => '526', 'name_en' => 'Iceland', 'name_ar' => 'ايسلندا'],
            ['code' => '527', 'name_en' => 'Liechtenstein', 'name_ar' => 'ليختنشتين'],
            ['code' => '528', 'name_en' => 'Luxembourg', 'name_ar' => 'لوكسمبورغ'],
            ['code' => '529', 'name_en' => 'Malta', 'name_ar' => 'مالطا'],
            ['code' => '530', 'name_en' => 'Monaco', 'name_ar' => 'موناكو'],
            ['code' => '531', 'name_en' => 'Norway', 'name_ar' => 'النرويج'],
            ['code' => '532', 'name_en' => 'San Marino', 'name_ar' => 'سان مارينو'],
            ['code' => '533', 'name_en' => 'Vatican City', 'name_ar' => 'مدينة الفاتيكان'],
            ['code' => '534', 'name_en' => 'Gibraltar', 'name_ar' => 'جبل طارق'],
            ['code' => '536', 'name_en' => 'Ukraine', 'name_ar' => 'اوكرانيا'],
            ['code' => '537', 'name_en' => 'Belarus', 'name_ar' => 'روسيا البيضاء'],
            ['code' => '539', 'name_en' => 'Armenia', 'name_ar' => 'ارمينيا'],
            ['code' => '540', 'name_en' => 'Moldova', 'name_ar' => 'مولدافيا'],
            ['code' => '541', 'name_en' => 'Georgia', 'name_ar' => 'جورجيا'],
            ['code' => '542', 'name_en' => 'Lithuania', 'name_ar' => 'ليتوانيا'],
            ['code' => '543', 'name_en' => 'Estonia', 'name_ar' => 'استونيا'],
            ['code' => '544', 'name_en' => 'Latvia', 'name_ar' => 'لاتفيا'],
            ['code' => '545', 'name_en' => 'Bosnia and Herzegovina', 'name_ar' => 'البوسنة والهرسك'],
            ['code' => '546', 'name_en' => 'Croatia', 'name_ar' => 'كرواتيا'],
            ['code' => '547', 'name_en' => 'Slovenia', 'name_ar' => 'سلوفينيا'],
            ['code' => '549', 'name_en' => 'Macedonia', 'name_ar' => 'مقدونيا'],
            ['code' => '552', 'name_en' => 'Czech Republic', 'name_ar' => 'تشيك'],
            ['code' => '553', 'name_en' => 'Slovakia', 'name_ar' => 'سلوفاكيا'],
            ['code' => '554', 'name_en' => 'Faroe Islands', 'name_ar' => 'جزر فيرو'],
            ['code' => '555', 'name_en' => 'France Metropolitan', 'name_ar' => 'ميتروبوليتان فرنسية'],

            // Americas (601-630)
            ['code' => '601', 'name_en' => 'United States', 'name_ar' => 'الولايات المتحدة'],
            ['code' => '602', 'name_en' => 'Argentina', 'name_ar' => 'الارجنتين'],
            ['code' => '603', 'name_en' => 'Barbados', 'name_ar' => 'بربادوس'],
            ['code' => '604', 'name_en' => 'Brazil', 'name_ar' => 'البرازيل'],
            ['code' => '605', 'name_en' => 'Panama', 'name_ar' => 'بنما'],
            ['code' => '606', 'name_en' => 'Trinidad and Tobago', 'name_ar' => 'ترينداد وتوباجو'],
            ['code' => '607', 'name_en' => 'Jamaica', 'name_ar' => 'جامايكا'],
            ['code' => '608', 'name_en' => 'Guyana', 'name_ar' => 'جوانا'],
            ['code' => '609', 'name_en' => 'Venezuela', 'name_ar' => 'فنزويلا'],
            ['code' => '610', 'name_en' => 'Canada', 'name_ar' => 'كندا'],
            ['code' => '611', 'name_en' => 'Colombia', 'name_ar' => 'كولمبيا'],
            ['code' => '612', 'name_en' => 'Bahamas', 'name_ar' => 'جزر البهاما'],
            ['code' => '613', 'name_en' => 'Costa Rica', 'name_ar' => 'كوستاريكا'],
            ['code' => '614', 'name_en' => 'Cuba', 'name_ar' => 'كوبا'],
            ['code' => '615', 'name_en' => 'Dominica', 'name_ar' => 'دومينيكا'],
            ['code' => '616', 'name_en' => 'Dominican Republic', 'name_ar' => 'جمهورية دمينكان'],
            ['code' => '617', 'name_en' => 'El Salvador', 'name_ar' => 'السلفادور'],
            ['code' => '618', 'name_en' => 'Grenada', 'name_ar' => 'جرانادا'],
            ['code' => '619', 'name_en' => 'Guatemala', 'name_ar' => 'جواتيمالا'],
            ['code' => '620', 'name_en' => 'Haiti', 'name_ar' => 'هايتي'],
            ['code' => '621', 'name_en' => 'Honduras', 'name_ar' => 'هوندوراس'],
            ['code' => '622', 'name_en' => 'Mexico', 'name_ar' => 'المكسيك'],
            ['code' => '623', 'name_en' => 'Nicaragua', 'name_ar' => 'نيكاراجوا'],
            ['code' => '624', 'name_en' => 'Saint Lucia', 'name_ar' => 'سانت لوسيا'],
            ['code' => '625', 'name_en' => 'Saint Vincent', 'name_ar' => 'سان فينسنت'],
            ['code' => '626', 'name_en' => 'Bolivia', 'name_ar' => 'بوليفيا'],
            ['code' => '627', 'name_en' => 'Chile', 'name_ar' => 'شيلي'],
            ['code' => '628', 'name_en' => 'Ecuador', 'name_ar' => 'اكوادور'],
            ['code' => '629', 'name_en' => 'Paraguay', 'name_ar' => 'باراجواي'],
            ['code' => '630', 'name_en' => 'Peru', 'name_ar' => 'بيرو'],

            // Oceania (701-702)
            ['code' => '701', 'name_en' => 'Australia', 'name_ar' => 'استراليا'],
            ['code' => '702', 'name_en' => 'New Zealand', 'name_ar' => 'نيوزيلندا'],
        ];

        foreach ($nafathCodes as $codeData) {
            NafathNationalityCode::updateOrCreate(
                ['code' => $codeData['code']],
                $codeData
            );
        }

        echo "Seeded " . count($nafathCodes) . " Nafath nationality codes successfully!\n";
    }
}