<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NationalitySeeder extends Seeder
{
    public function run()
    {
        $arabicNationalities = [
            'سعودي',
            'بحريني',
            'كويتي',
            'قطري',
            'عماني',
            'إماراتي',
            'جزائري',
            'جزر القمر',
            'جيبوتي',
            'مصري',
            'عراقي',
            'أردني',
            'لبناني',
            'ليبيا',
            'موريتاني',
            'مغربي',
            'فلسطيني',
            'صومالي',
            'سوداني',
            'سوري',
            'تونسي',
            'يمني',
            'أفغاني',
            'ألباني',
            'أذربيجان',
            'بنغلاديش',
            'بنين',
            'بروناى',
            'بوركينافاسو',
            'كاميروني',
            'تشادي',
            'ساحل العاج',
            'جابوني',
            'جامبي',
            'غيني',
            'غيني (بيساو)',
            'أندونيسي',
            'كازاخستاني',
            'قرقيزي',
            'ماليزية',
            'جزر المالديف',
            'مالي',
            'موزمبيق',
            'النيجر',
            'نيجيري',
            'باكستاني',
            'سنغالي',
            'سيراليون',
            'سورينام',
            'طاجيكي',
            'توجو',
            'تركي',
            'تركماني',
            'أوغندي',
            'أوزبكي',
            'أرميني',
            'بوتاني',
            'بريطاني',
            'كمبودي',
            'صيني',
            'جزيرة كوكوس',
            'جورجي',
            'هونج كونج',
            'هندي',
            'ياباني',
            'كوري شمالي',
            'كوري جنوبي',
            'لاوسي',
            'ماكاو',
            'ولايات ميكرونيزيا الموحدة',
            'منغولي',
            'بورمي',
            'نيبالي',
            'فلبيني',
            'سنغافوري',
            'سريلانكي',
            'تايواني',
            'تايلاندي',
            'تيموري',
            'فيتنامي',
            'أنغولي',
            'بوتسوانا',
            'بوروندي',
            'الرأاس الأخضر',
            'افريقيا الوسطى',
            'كونغو/برازافيل',
            'كونغو/زائير',
            'غينيا (الإستوائية)',
            'الإريترية',
            'أثيوبي',
            'غاني',
            'الكيني',
            'ليسوتو',
            'ليبري',
            'مدغشقر',
            'مالاوى',
            'موريشيوس',
            'مايوتي',
            'نامبي',
            'جزيرة لا ريونيون',
            'رواندي',
            'سانت هيلينة',
            'ساو تومي وبرينسيب',
            'سيشل',
            'جنوب افريقيا',
            'جنوب السودان',
            'سوازي',
            'تنزاني',
            'الصحراء الغربية',
            'زامبيا',
            'زيمبابوي',
            'نمساوي',
            'بلجيكي',
            'بلغاري',
            'كرواتي',
            'قبرصي',
            'تشيكي',
            'دانماركي',
            'إستوني',
            'فنلدي',
            'فرنسي',
            'ألماني',
            'يوناني',
            'هنغاري',
            'أيرلندي',
            'إيطالي',
            'لاتفي',
            'لاتوني',
            'لوكسمبورغ',
            'مالطي',
            'هولندي',
            'بولندي',
            'برتغالي',
            'روماني',
            'سلوفاكي',
            'سلوفاني',
            'الإسبانية',
            'السويدية',
            'البريطانية',
            'جزيرة أولاند',
            'أندورا',
            'بيلاروسي',
            'بوسني',
            'جزر فارو',
            'جبل طارق',
            'جيرنسي',
            'الكرسي الرسولي',
            'أيسلندي',
            'جيرزي',
            'جزر القنال',
            'ليختنشتاين',
            'مقدوني',
            'مولدوفي',
            'موناكو',
            'الجبل الأسود',
            'نرويجي',
            'روسي',
            'سان مارينو',
            'صربي',
            'سفالبارد وجون مين',
            'سويسري',
            'أوكراني',
            'أنغيلا',
            'أنتيجوا وبربودا',
            'باهامس',
            'بربادوس',
            'بليز',
            'برمودا',
            'كندي',
            'جزر كايمان',
            'كوستاريكي',
            'كوبي',
            'الدومينيكا',
            'دومينيكي',
            'السلفادور',
            'جرينلاند',
            'غرينادا',
            'غوادلوب',
            'غواتيمالي',
            'هاييتي',
            'هندوراسي',
            'جامايكي',
            'مارتينيك',
            'مكسيكي',
            'مونتسرات',
            'نيكاراغواي',
            'بنمي',
            'بورتوريكوي',
            'سان بارتيلمي',
            'سانت كيتس ونيفيس',
            'سانت لوسيا',
            'سانت مارتن الحزر الفرنسي',
            'سانت بيير وميكلون',
            'سانت فنسنت والجرينادينز',
            'سينت مارتن الجزء الهولندي',
            'ترينيدا وتوباجو',
            'جزيرة تركس وكايكوس',
            'جزر الولايات المتحدة الصغيرة النائية',
            'أمريكي',
            'جزر العذراء البريطانية',
            'جزر العذراء الأمريكية',
            'أرجنتيني',
            'أروبا',
            'بوليفي',
            'بونير، سينت أوستاتيوس وسابا',
            'برازيلي',
            'شيلي',
            'كولومبي',
            'كوراساو',
            'اكوادوري',
            'جزيرة فوكلاند',
            'غيانا',
            'غيانا',
            'باراغواي',
            'بيرو',
            'جورجيا الجنوبية',
            'أوروغواي',
            'فنزويلي',
            'ساموا الأمريكية',
            'أسترالي',
            'جزيرة كريسماس',
            'جزيرة كوك',
            'فيجي',
            'بولينيزية الفرنسية',
            'الأقاليم الجنوبية الفرنسية',
            'غوام',
            'جزيرة هيرد وجزر ماكدونالد',
            'كيريباتي',
            'جزر مارشال',
            'ناورو',
            'نيوكاليدوني',
            'نيوزيلندي',
            'نيوي',
            'جزيرة نورفولك',
            'ماريانا الشمالية',
            'بالاو',
            'بابوا غينيا الجديدة',
            'جزر بيتكيرن',
            'ساموا',
            'جزيرة سليمان',
            'توكيلاو',
            'تونجا',
            'توفالو',
            'فانواتو',
            'واليس وفوتونا',
            'القارة القطبية الجنوبية',
            'جزيرة بوفيت',
        ];

        $englishNationalities = [
            'Saudi',
            'Bahraini',
            'Kuwaiti',
            'Qatari',
            'Omani',
            'Emirati',
            'Algerian',
            'Comorian',
            'Djiboutian',
            'Egyptian',
            'Iraqi',
            'Jordanian',
            'Lebanese',
            'Libyan',
            'Mauritanian',
            'Moroccan',
            'Palestinian',
            'Somali',
            'Sudanese',
            'Syrian',
            'Tunisian',
            'Yemeni',
            'Afghan',
            'Albanian',
            'Azerbaijan',
            'Bangladesh',
            'Beninese',
            'Bruneian',
            'Burkinabé',
            'Cameroonian',
            'Chadian',
            'Ivorian',
            'Gabonese',
            'Gambian',
            'Guinean',
            'Bissau-Guinean',
            'Indonesian',
            'Kazakhstani',
            'Kyrgyzstani',
            'Malaysian',
            'Maldivian',
            'Malian',
            'Mozambican',
            'Nigerien',
            'Nigerian',
            'Pakistani',
            'Senegalese',
            'Sierra Leonean',
            'Surinamese',
            'Tajikistani',
            'Togolese',
            'Turkish',
            'Turkmen',
            'Ugandan',
            'Uzbekistani',
            'Armenian',
            'Bhutanese',
            'British',
            'Cambodian',
            'Chinese',
            'Cocos Island',
            'Georgian',
            'Hong Kong',
            'Indian',
            'Japanese',
            'North Korean',
            'South Korean',
            'Laotian',
            'Macanese',
            'Micronesian',
            'Mongolian',
            'Burmese',
            'Nepali',
            'Philippine',
            'Singaporean',
            'Sri Lankan',
            'Taiwanese',
            'Thai',
            'Timorese',
            'Vietnamese',
            'Angolan',
            'Botswanan',
            'Burundian',
            'Cabo Verdean',
            'Central African',
            'Congolese',
            'Congolese',
            'Equatorial Guinean',
            'Eritrean',
            'Ethiopian',
            'Ghanaian',
            'Kenyan',
            'Basotho',
            'Liberian',
            'Malagasy',
            'Malawian',
            'Mauritian',
            'Mahoran',
            'Namibian',
            'Réunionese',
            'Rwandan',
            'Saint Helenian',
            'São Toméan',
            'Seychellois',
            'South African',
            'South Sudanese',
            'Swazi',
            'Tanzanian',
            'Sahrawi',
            'Zambian',
            'Zimbabwean',
            'Austrian',
            'Belgian',
            'Bulgarian',
            'Croatian',
            'Cypriot',
            'Czech',
            'Danish',
            'Estonian',
            'Finnish',
            'French',
            'German',
            'Greek',
            'Hungarian',
            'Irish',
            'Italian',
            'Latvian',
            'Lithuanian',
            'Luxembourg',
            'Maltese',
            'Dutch',
            'Polish',
            'Portuguese',
            'Romanian',
            'Slovak',
            'Slovenian',
            'Spanish',
            'Swedish',
            'British',
            'Åland Island',
            'Andorran',
            'Belarusian',
            'Bosnian',
            'Faroese',
            'Gibraltar',
            'Guernsey',
            'Holy See',
            'Icelandic',
            'Manx',
            'Channel Island',
            'Liechtenstein',
            'Macedonian',
            'Moldovan',
            'Monacan',
            'Montenegrin',
            'Norwegian',
            'Russian',
            'Sammarinese',
            'Serbian',
            'Svalbard and Jan Mayen',
            'Swiss',
            'Ukrainian',
            'Anguillan',
            'Antiguan, Barbudan',
            'Bahamian',
            'Barbadian',
            'Belizean',
            'Bermudian',
            'Canadian',
            'Caymanian',
            'Costa Rican',
            'Cuban',
            'Dominican',
            'Dominican',
            'Salvadoran',
            'Greenlandic',
            'Grenadian',
            'Guadeloupe',
            'Guatemalan',
            'Haitian',
            'Honduran',
            'Jamaican',
            'Martinican',
            'Mexican',
            'Montserratian',
            'Nicaraguan',
            'Panamanian',
            'Puerto Rican',
            'Barthélemois',
            'Kittitian, Nevisian',
            'Saint Lucian',
            'Saint Martin French part',
            'French',
            'Saint Vincentian',
            'Sint Maarten Dutch part',
            'Trinidadian, Tobagonian',
            'Turks and Caicos Island',
            'United States Minor Outlying Islands',
            'American',
            'British Virgin Island',
            'U.S. Virgin Island',
            'Argentine',
            'Aruban',
            'Bolivian',
            'Bonaire, Sint Eustatius and Saba',
            'Brazilian',
            'Chilean',
            'Colombian',
            'Curacaoan',
            'Ecuadorian',
            'Falkland Island',
            'French Guianese',
            'Guyanese',
            'Paraguayan',
            'Peruvian',
            'South Georgia',
            'Uruguayan',
            'Venezuelan',
            'American Samoan',
            'Australian',
            'Christmas Island',
            'Cook Island',
            'Fijian',
            'French Polynesian',
            'French Southern Territories',
            'Guamanian',
            'Heard Island',
            'I-Kiribati',
            'Marshallese',
            'Nauruan',
            'New Caledonian',
            'New Zealand',
            'Niuean',
            'Norfolk Island',
            'Northern Marianan',
            'Palauan',
            'Papua New Guinean',
            'Pitcairn Island',
            'Samoan',
            'Solomon Island',
            'Tokelauan',
            'Tongan',
            'Tuvaluan',
            'Vanuatuan',
            'Wallis and Futuna',
            'Antarctic',
            'Bouvet Island',
        ];

        if (count($arabicNationalities) !== count($englishNationalities)) {
            throw new \Exception('The number of Arabic and English nationalities must match.');
        }

        foreach ($arabicNationalities as $index => $arabNationality) {
            $englishNationality = $englishNationalities[$index];

            DB::table('nationalities')->insert([
                'name' => json_encode([
                    'ar' => $arabNationality,
                    'en' => $englishNationality,
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
