import type { Metadata } from "next";
import { IBM_Plex_Sans_Arabic } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages, getTranslations } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import Providers from "@/providers";

import "../globals.css";
import "@ant-design/v5-patch-for-react-19";
import { Theme } from "@/lib/interfaces";
import { defaultTheme } from "@/store/theme";
import { getBrandTheme } from "@/lib/actions";

// const font = IBM_Plex_Sans_Arabic({
//   subsets: ["latin", "arabic"],
//   weight: ["400", "500", "600", "700"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export async function generateMetadata(): Promise<Metadata> {
  const locale = await getLocale();
  const t = await getTranslations({ locale, namespace: "meta" });
  return {
    title: t("title"),
  };
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: Locale }>;
}>) {
  const { locale } = await params;
  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale)) {
    notFound();
  }

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();
  const t = await getTranslations({ locale, namespace: "meta" });
  // handle the theme
  const dynamicTheme = await getBrandTheme();
  const theme: Theme = {
    ...defaultTheme,
    ...Object.fromEntries(
      Object.entries(dynamicTheme || {}).map(([key, value]) => [
        key,
        value ?? defaultTheme[key as keyof typeof defaultTheme],
      ])
    ),
  };
  function addThemeVars(theme: Theme) {
    if (!theme) return;
    const themeVars = Object.entries(theme).reduce((acc, [key, value]) => {
      const kebabKey = key
        .replace(/_/g, "-")
        .replace(/([a-z])([A-Z])/g, "$1-$2")
        .toLowerCase();
      acc[`--${kebabKey}`] = value;
      return acc;
    }, {} as Record<string, string | number>);

    return themeVars;
  }

  return (
    <html
      lang={locale}
      dir={locale === "ar" ? "rtl" : "ltr"}
      style={addThemeVars(theme)}
    >
      <head>
        {/* <title>{theme?.metaData?.title || t("title")}</title> */}
        {theme.favicon && <link rel="icon" href={theme.favicon} />}
        <link
          href={`https://fonts.googleapis.com/css2?family=${encodeURIComponent(
            String(dynamicTheme?.font)
          )}:wght@100;300;400;500;700;900&display=swap`}
          rel="stylesheet"
        />
      </head>
      <body className={`antialiased`}>
        {" "}
        <NextIntlClientProvider messages={messages}>
          <Providers theme={theme}>{children}</Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
