import type { Metadata } from "next";
import { IBM_Plex_Sans_Arabic } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages, getTranslations } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import Providers from "@/providers";

import "../globals.css";
import "@ant-design/v5-patch-for-react-19";
import { Theme } from "@/lib/interfaces";
import { defaultTheme } from "@/store/theme";
import { getBrandTheme } from "@/lib/actions";

// const font = IBM_Plex_Sans_Arabic({
//   subsets: ["latin", "arabic"],
//   weight: ["400", "500", "600", "700"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export async function generateMetadata(): Promise<Metadata> {
  const locale = await getLocale();
  const t = await getTranslations({ locale, namespace: "meta" });
  return {
    title: t("title"),
  };
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: Locale }>;
}>) {
  const { locale } = await params;
  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale)) {
    notFound();
  }

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();
  const t = await getTranslations({ locale, namespace: "meta" });
  // handle the theme
  const dynamicTheme = await getBrandTheme();
  const theme: Theme = {
    ...defaultTheme,
    ...Object.fromEntries(
      Object.entries(dynamicTheme || {}).map(([key, value]) => [
        key,
        value ?? defaultTheme[key as keyof typeof defaultTheme],
      ])
    ),
  };
  function adjustColor(hex: string, percent: number): string {
    const num = parseInt(hex.replace("#", ""), 16);
    const amt = Math.round(2.55 * percent);
    const R = Math.min(255, Math.max(0, (num >> 16) + amt));
    const G = Math.min(255, Math.max(0, ((num >> 8) & 0x00ff) + amt));
    const B = Math.min(255, Math.max(0, (num & 0x0000ff) + amt));
    return `#${(0x1000000 + R * 0x10000 + G * 0x100 + B).toString(16).slice(1)}`;
  }

  function addThemeVars(theme: Theme) {
    if (!theme) return;
    const themeVars = Object.entries(theme).reduce((acc, [key, value]) => {
      const kebabKey = key
        .replace(/_/g, "-")
        .replace(/([a-z])([A-Z])/g, "$1-$2")
        .toLowerCase();
      acc[`--${kebabKey}`] = value;
      return acc;
    }, {} as Record<string, string | number>);

    // Also set DGA design system variables server-side for initial render
    const primary = theme.primary_color;
    const secondary = theme.secondary_color;
    if (primary) {
      themeVars["--dga-primary-500"] = primary;
      themeVars["--dga-primary-400"] = adjustColor(primary, 20);
      themeVars["--dga-primary-300"] = adjustColor(primary, 40);
      themeVars["--dga-primary-200"] = adjustColor(primary, 60);
      themeVars["--dga-primary-100"] = adjustColor(primary, 80);
      themeVars["--dga-primary-50"] = adjustColor(primary, 90);
      themeVars["--dga-primary-700"] = adjustColor(primary, -20);
      themeVars["--dga-primary-800"] = adjustColor(primary, -40);
      themeVars["--dga-primary-900"] = adjustColor(primary, -60);
    }
    if (secondary) {
      themeVars["--dga-primary-600"] = secondary;
    }

    return themeVars;
  }

  return (
    <html
      lang={locale}
      dir={locale === "ar" ? "rtl" : "ltr"}
      style={addThemeVars(theme)}
    >
      <head>
                        {/* <title>{theme?.metaData?.title || t("title")}</title> */}
        {theme.favicon && <link rel="icon" href={theme.favicon} />}
        {theme.font && theme.font !== "undefined" && (
          <link
            href={`https://fonts.googleapis.com/css2?family=${encodeURIComponent(
              theme.font
            )}:wght@100;300;400;500;700;900&display=swap`}
            rel="stylesheet"
          />
        )}      </head>
      <body className={`antialiased`}>
        {" "}
        <NextIntlClientProvider messages={messages}>
          <Providers theme={theme}>{children}</Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
